# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 13:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('entertainer_type', models.CharField(choices=[('Wedding Band', 'Wedding Band'), ('DJ', 'DJ')], default='Wedding Band', max_length=300)),
                ('location', models.CharField(choices=[('Leinster', 'Leinster'), ('Ulster', 'Ulster'), ('Munster', 'Munster'), ('Connacht', 'Connacht')], default='Leinster', max_length=300)),
                ('facebook', models.CharField(max_length=300, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.CharField(max_length=300, validators=[django.core.validators.URLValidator()])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
